import PDFDocument from 'pdfkit'
import type { LegalEntity, ProcurementRequest, Project, PurchaseOrder, Supplier } from '../../src/domain.js'

export async function renderPurchaseOrderPdf(input:{order:PurchaseOrder;request:ProcurementRequest;supplier:Supplier;project:Project;entity?:LegalEntity}){
  const chunks:Buffer[]=[];const document=new PDFDocument({size:'A4',margin:48,info:{Title:`Bestelbon ${input.order.number}`}});document.on('data',(chunk:Buffer)=>chunks.push(chunk));const done=new Promise<Buffer>(resolve=>document.on('end',()=>resolve(Buffer.concat(chunks))));
  document.fontSize(20).fillColor('#16324f').text(input.entity?.name??'BouwFlow');document.fontSize(10).fillColor('#52606d').text(input.entity?.vatNumber??'');document.moveDown();document.fontSize(18).fillColor('#111827').text(`BESTELBON ${input.order.number}`);document.fontSize(10).text(`Besteldatum: ${input.order.orderDate}`);document.text(`Verwachte levering: ${input.order.expectedDeliveryDate}`);document.moveDown();document.fontSize(12).text(`Leverancier: ${input.supplier.name}`);document.fontSize(10).text(`${input.supplier.contactName} · ${input.supplier.email}`);document.text(`Project: ${input.project.number} · ${input.project.name}`);document.text(`Inkoopdossier: ${input.request.number}`);document.moveDown();
  const left=48;document.fontSize(9).fillColor('#ffffff').rect(left,document.y,499,22).fill('#16324f');const headerY=document.y+7;document.text('Omschrijving',left+6,headerY,{width:245});document.text('Aantal',left+255,headerY,{width:60,align:'right'});document.text('Eenheid',left+325,headerY,{width:55});document.text('Prijs',left+385,headerY,{width:50,align:'right'});document.text('Totaal',left+440,headerY,{width:55,align:'right'});document.y+=25;document.fillColor('#111827');
  for(const line of input.order.lines??[]){const y=document.y;const total=line.orderedQuantity*line.unitPrice;document.text(line.description,left+6,y,{width:245});document.text(line.orderedQuantity.toFixed(2),left+255,y,{width:60,align:'right'});document.text(line.unit,left+325,y,{width:55});document.text(line.unitPrice.toFixed(2),left+385,y,{width:50,align:'right'});document.text(total.toFixed(2),left+440,y,{width:55,align:'right'});document.moveDown(1.2);document.strokeColor('#e5e7eb').moveTo(left,document.y).lineTo(547,document.y).stroke();document.moveDown(.4)}
  document.moveDown();document.fontSize(13).text(`Totaal excl. btw: EUR ${input.order.amount.toFixed(2)}`,{align:'right'});document.moveDown();document.fontSize(9).fillColor('#52606d').text('Deze bestelbon is digitaal gegenereerd vanuit het goedgekeurde BouwFlow-inkoopdossier. Vermeld bestelbon- en projectnummer op leveringsbon en factuur.');document.end();return done
}
