import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BadgeCheck, CalendarCheck, CheckCircle2, ClipboardCheck, ExternalLink, Fingerprint, HardHat, History, MapPin, Plus, Printer, QrCode, RefreshCw, Settings2, ShieldCheck, UserCheck, Users, XCircle } from 'lucide-react'
import QRCode from 'qrcode'
import type { BouwFlowState, CheckinatworkParticipantInput, CheckinatworkRegistrationSource, CheckinatworkSiteInput } from './domain'
import { CHECKINATWORK_THRESHOLD, checkinatworkDashboard, checkinatworkRequirement } from './checkinatwork'
import type { useBouwFlowStore } from './store'

type Actions = ReturnType<typeof useBouwFlowStore>['actions']
type WorkspaceTab = 'Vandaag' | 'Voorbereiding' | 'Compliance' | 'Audit'

const formatDateTime = (value?: string) => value ? new Intl.DateTimeFormat('nl-BE', { dateStyle:'short', timeStyle:'short' }).format(new Date(value)) : '\u2014'
const money = (value:number) => new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value)
const statusClass = (status:string) => status === 'Officieel bevestigd' || status === 'Extern geregistreerd' ? 'ok' : status === 'Geweigerd' ? 'error' : status === 'Geannuleerd' ? 'muted' : 'pending'

export function CheckinatworkWorkspace({ state, actions, projectId }: { state:BouwFlowState; actions:Actions; projectId:string }) {
  const [tab,setTab]=useState<WorkspaceTab>('Vandaag')
  const latestRegistrationDate=state.checkinatworkRegistrations.filter(item=>item.projectId===projectId).sort((a,b)=>b.registrationDate.localeCompare(a.registrationDate))[0]?.registrationDate
  const [registrationDate,setRegistrationDate]=useState(latestRegistrationDate??new Date().toISOString().slice(0,10))
  const [source,setSource]=useState<CheckinatworkRegistrationSource>('QR')
  const project=state.projects.find(item=>item.id===projectId)
  const dashboard=useMemo(()=>checkinatworkDashboard(state,projectId,registrationDate),[state,projectId,registrationDate])
  const site=dashboard.site
  const [editingSite,setEditingSite]=useState(false)
  const [addingParticipant,setAddingParticipant]=useState(false)
  const [posterQr,setPosterQr]=useState('')
  useEffect(()=>{setRegistrationDate(latestRegistrationDate??new Date().toISOString().slice(0,10))},[projectId,latestRegistrationDate])
  useEffect(()=>{if(!site){setPosterQr('');return}const url=new URL('/site',window.location.origin);url.searchParams.set('cawSite',site.id);void QRCode.toDataURL(url.toString(),{width:360,margin:1,errorCorrectionLevel:'M',color:{dark:'#0d2832',light:'#ffffff'}}).then(setPosterQr)},[site])
  if(!project)return null
  const requirement=checkinatworkRequirement(project,site)
  return <section className="caw-workspace" aria-label="Aanwezigheden en Checkinatwork">
    <header className="caw-header">
      <div className="caw-title"><span className="caw-logo"><ShieldCheck size={23}/></span><div><p className="eyebrow">Belgische werfcompliance</p><h2>Aanwezigheden &amp; Checkinatwork</h2><span>{project.number} · {project.name}</span></div></div>
      <div className="caw-header-status"><span className={`caw-pill ${requirement.applicability==='Verplicht'?'required':'neutral'}`}>{requirement.applicability}</span><span className={`caw-pill ${site?.environment==='Productie'?'production':'simulation'}`}>{site?.environment??'Niet geconfigureerd'}</span></div>
    </header>
    <nav className="caw-tabs" aria-label="Checkinatwork werkruimte">{(['Vandaag','Voorbereiding','Compliance','Audit'] as WorkspaceTab[]).map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item==='Vandaag'?<CalendarCheck size={15}/>:item==='Voorbereiding'?<Users size={15}/>:item==='Compliance'?<ClipboardCheck size={15}/>:<History size={15}/>} {item}</button>)}</nav>
    {tab==='Vandaag'&&<>
      <div className="caw-day-toolbar"><label>Werkdag<input type="date" value={registrationDate} onChange={event=>setRegistrationDate(event.target.value)}/></label><label>Registratiebron<select value={source} onChange={event=>setSource(event.target.value as CheckinatworkRegistrationSource)}>{['QR','Badge','Kiosk','Mobiel','Planning','Manueel','Import'].map(item=><option key={item}>{item}</option>)}</select></label><button className="secondary" onClick={()=>setRegistrationDate(new Date().toISOString().slice(0,10))}><RefreshCw size={14}/>Vandaag</button></div>
      <div className="caw-kpis"><article><span>Verwacht</span><strong>{dashboard.expected}</strong><Users size={18}/></article><article className="ok"><span>Officieel bevestigd</span><strong>{dashboard.confirmed}</strong><BadgeCheck size={18}/></article><article className="pending"><span>Te verwerken</span><strong>{dashboard.pending}</strong><RefreshCw size={18}/></article><article className="error"><span>Geweigerd</span><strong>{dashboard.rejected}</strong><XCircle size={18}/></article></div>
      {dashboard.alerts.length>0&&<div className="caw-alerts">{dashboard.alerts.slice(0,8).map(alert=><article key={alert.id} data-severity={alert.severity}><AlertTriangle size={16}/><div><strong>{alert.title}</strong><span>{alert.detail}</span></div><em>{alert.severity}</em></article>)}</div>}
      <div className="caw-presence-list">{dashboard.participants.map(participant=>{const registration=dashboard.latestByParticipant.get(participant.id);return <article key={participant.id}><span className="caw-avatar"><HardHat size={17}/></span><div className="caw-person"><strong>{participant.displayName}</strong><span>{participant.employerName} · {participant.participantType}</span><small>{participant.identifierType} •••• {participant.identifierLast4}{participant.limosaExpiresOn?` · Limosa tot ${participant.limosaExpiresOn}`:''}</small></div><div className="caw-receipt">{registration?.receiptNumber?<><strong>{registration.receiptNumber}</strong><span>{formatDateTime(registration.confirmedAt)}</span></>:<span>Nog geen ontvangstnummer</span>}</div><span className={`caw-status ${statusClass(registration?.status??'Gepland')}`}>{registration?.status??'Gepland'}</span><div className="caw-row-actions">{!registration||['Geannuleerd','Geweigerd'].includes(registration.status)?<button className="primary" disabled={!site||!participant.identityVerified} onClick={()=>site&&void actions.registerCheckinatworkPresence({siteId:site.id,participantId:participant.id,registrationDate,source})}><UserCheck size={14}/>Registreren</button>:registration.status==='Officieel bevestigd'?<button className="secondary" onClick={()=>void actions.cancelCheckinatworkPresence(registration.id,'PLANNING')}><XCircle size={14}/>Annuleren</button>:null}</div></article>})}{!dashboard.participants.length&&<div className="caw-empty"><Users size={28}/><strong>Nog geen personen voorbereid</strong><span>Voeg werknemers en onderaannemers toe onder Voorbereiding.</span></div>}</div>
    </>}
    {tab==='Voorbereiding'&&<>
      <div className="caw-section-head"><div><p className="eyebrow">Ploegvoorbereiding</p><h3>Personen en identiteiten</h3><span>INSZ- en Limosa-waarden worden alleen naar de beveiligde adapter gestuurd; BouwFlow bewaart een afgeschermde referentie.</span></div><button className="primary" onClick={()=>setAddingParticipant(true)}><Plus size={15}/>Persoon toevoegen</button></div>
      <div className="caw-preparation-grid"><section><h4>Geplande ploeg</h4>{dashboard.participants.map(item=><article className="caw-identity-card" key={item.id}><Fingerprint size={18}/><div><strong>{item.displayName}</strong><span>{item.employerName}</span><small>{item.identifierType} eindigt op {item.identifierLast4}</small></div><span className={`caw-status ${item.identityVerified?'ok':'error'}`}>{item.identityVerified?'Identiteit gereed':'Actie vereist'}</span></article>)}</section><aside className="caw-poster">{posterQr?<img className="caw-poster-qr" src={posterQr} alt={`Scanbare Checkinatwork-werfcode voor ${project.name}`}/>:<QrCode size={54}/>}<p className="eyebrow">Scanbare werfposter</p><h3>{site?.workPlaceId||'Werkplaatsnummer ontbreekt'}</h3><span>{site?.address||project.name}</span><small>Scan op de werf en bevestig vóór de werkzaamheden starten.</small><button className="secondary" onClick={()=>window.print()}><Printer size={14}/>Poster afdrukken</button></aside></div>
      {addingParticipant&&<ParticipantForm state={state} projectId={projectId} onClose={()=>setAddingParticipant(false)} onSubmit={input=>{void actions.createCheckinatworkParticipant(input);setAddingParticipant(false)}}/>}
    </>}
    {tab==='Compliance'&&<>
      <div className="caw-compliance-summary"><article><span>Contractwaarde</span><strong>{money(project.contractValue)}</strong><small>Drempel {money(site?.thresholdAmount??CHECKINATWORK_THRESHOLD)} excl. btw</small></article><article><span>Aangifte van Werken</span><strong>{site?.declarationNumber||'Ontbreekt'}</strong><small>RSZ-werkplaats {site?.workPlaceId||'niet ingevuld'}</small></article><article><span>Connector</span><strong>{state.checkinatworkIntegrationStatus.provider}</strong><small>{state.checkinatworkIntegrationStatus.protocol}</small></article></div>
      <div className={`caw-production-gate ${state.checkinatworkIntegrationStatus.productionEnabled?'ready':'locked'}`}><ShieldCheck size={22}/><div><strong>{state.checkinatworkIntegrationStatus.productionEnabled?'Productieverzending vrijgegeven':'Productieverzending veilig geblokkeerd'}</strong><span>{state.checkinatworkIntegrationStatus.productionConfigured?'Adapter geconfigureerd; administratieve vrijgave vereist.':'Configureer GlobalSign, technische gebruiker en de beveiligde RSZ-adapter.'}</span></div></div>
      <div className="caw-requirement"><CheckCircle2 size={20}/><div><strong>Automatische beoordeling: {requirement.applicability}</strong><span>{requirement.reason}</span></div><button className="secondary" onClick={()=>setEditingSite(true)}><Settings2 size={14}/>{site?'Configuratie wijzigen':'Werkplaats configureren'}</button></div>
      <div className="caw-links"><a href="https://www.socialsecurity.be/site_nl/employer/applics/checkinatwork/index.htm" target="_blank" rel="noreferrer">Officieel Checkinatwork-portaal <ExternalLink size={13}/></a><a href="https://www.socialsecurity.be/site_nl/general/helpcentre/soa/presence_registration.htm" target="_blank" rel="noreferrer">PresenceRegistration v1.11 <ExternalLink size={13}/></a></div>
      {editingSite&&<SiteForm projectId={projectId} projectName={project.name} current={site} productionReady={state.checkinatworkIntegrationStatus.productionConfigured} onClose={()=>setEditingSite(false)} onSubmit={input=>{void actions.configureCheckinatworkSite(input);setEditingSite(false)}}/>}
    </>}
    {tab==='Audit'&&<div className="caw-audit-list">{state.checkinatworkAuditEvents.filter(item=>item.projectId===projectId).sort((a,b)=>b.at.localeCompare(a.at)).map(item=><article key={item.id}><span className="caw-audit-icon"><History size={15}/></span><div><strong>{item.action.replaceAll('_',' ')}</strong><span>{item.detail}</span><small>{item.actor} · {formatDateTime(item.at)}</small></div></article>)}{!state.checkinatworkAuditEvents.some(item=>item.projectId===projectId)&&<div className="caw-empty">Nog geen auditevents.</div>}</div>}
  </section>
}

function ParticipantForm({state,projectId,onClose,onSubmit}:{state:BouwFlowState;projectId:string;onClose:()=>void;onSubmit:(input:CheckinatworkParticipantInput)=>void}){
  const [employeeId,setEmployeeId]=useState('')
  const [subcontractorId,setSubcontractorId]=useState('')
  const [displayName,setDisplayName]=useState('')
  const [employerName,setEmployerName]=useState('BouwFlow Construct NV')
  const [companyNumber,setCompanyNumber]=useState('0502635588')
  const [participantType,setParticipantType]=useState<CheckinatworkParticipantInput['participantType']>('Werknemer')
  const [identifierType,setIdentifierType]=useState<CheckinatworkParticipantInput['identifierType']>('INSZ')
  const [identifier,setIdentifier]=useState('')
  const [limosaExpiresOn,setLimosaExpiresOn]=useState('')
  const chooseEmployee=(id:string)=>{setEmployeeId(id);const item=state.employees.find(entry=>entry.id===id);if(item){setDisplayName(`${item.firstName} ${item.lastName}`);setEmployerName(state.legalEntities.find(entity=>entity.id===item.legalEntityId)?.name??'BouwFlow Construct NV');setSubcontractorId('');setParticipantType('Werknemer')}}
  const chooseSubcontractor=(id:string)=>{setSubcontractorId(id);const item=state.subcontractors.find(entry=>entry.id===id);if(item){setDisplayName(item.contactName);setEmployerName(item.name);setCompanyNumber(item.vatNumber);setEmployeeId('');setParticipantType('Onderaannemer')}}
  return <div className="modal-backdrop"><form className="modal caw-modal" onSubmit={event=>{event.preventDefault();onSubmit({projectId,employeeId:employeeId||undefined,subcontractorId:subcontractorId||undefined,displayName,employerName,employerCompanyNumber:companyNumber,participantType,identifierType,identifier,limosaExpiresOn:limosaExpiresOn||undefined,active:true})}}><header className="modal-head"><div><p className="eyebrow">Veilige werfidentiteit</p><h2>Persoon voorbereiden</h2><span>De volledige identificatie wordt niet in de browserstatus of auditlog bewaard.</span></div><button type="button" className="icon-button" aria-label="Sluiten" onClick={onClose}><XCircle size={19}/></button></header><div className="form-grid"><label>Interne medewerker<select value={employeeId} onChange={event=>chooseEmployee(event.target.value)}><option value="">Niet gekoppeld</option>{state.employees.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></label><label>Onderaannemer<select value={subcontractorId} onChange={event=>chooseSubcontractor(event.target.value)}><option value="">Niet gekoppeld</option>{state.subcontractors.filter(item=>item.projectIds.includes(projectId)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="full">Naam<input required value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label>Werkgever<input required value={employerName} onChange={event=>setEmployerName(event.target.value)}/></label><label>Ondernemingsnummer<input value={companyNumber} onChange={event=>setCompanyNumber(event.target.value)}/></label><label>Hoedanigheid<select value={participantType} onChange={event=>setParticipantType(event.target.value as typeof participantType)}>{['Werknemer','Zelfstandige','Interim','Onderaannemer','Architect','Veiligheidsco\u00f6rdinator'].map(item=><option key={item}>{item}</option>)}</select></label><label>Identificatie<select value={identifierType} onChange={event=>setIdentifierType(event.target.value as typeof identifierType)}><option>INSZ</option><option>Limosa</option></select></label><label className="full">{identifierType}<input required inputMode="numeric" autoComplete="off" value={identifier} minLength={identifierType==='INSZ'?11:17} maxLength={identifierType==='INSZ'?11:17} onChange={event=>setIdentifier(event.target.value.replace(/\D/g,''))}/></label>{identifierType==='Limosa'&&<label>Limosa geldig tot<input required type="date" value={limosaExpiresOn} onChange={event=>setLimosaExpiresOn(event.target.value)}/></label>}</div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Annuleren</button><button className="primary" disabled={!displayName||!employerName||identifier.length!==(identifierType==='INSZ'?11:17)}><Fingerprint size={15}/>Veilig provisioneren</button></div></form></div>
}

function SiteForm({projectId,projectName,current,productionReady,onClose,onSubmit}:{projectId:string;projectName:string;current?:BouwFlowState['checkinatworkSites'][number];productionReady:boolean;onClose:()=>void;onSubmit:(input:CheckinatworkSiteInput)=>void}){
  const [form,setForm]=useState<CheckinatworkSiteInput>(current?{projectId:current.projectId,declarationNumber:current.declarationNumber,workPlaceId:current.workPlaceId,declarantCompanyNumber:current.declarantCompanyNumber,applicability:current.applicability,applicabilityReason:current.applicabilityReason,thresholdAmount:current.thresholdAmount,startDate:current.startDate,plannedEndDate:current.plannedEndDate,provisionalAcceptanceOn:current.provisionalAcceptanceOn,address:current.address,latitude:current.latitude,longitude:current.longitude,geofenceRadiusMeters:current.geofenceRadiusMeters,environment:current.environment,active:current.active}:{projectId,declarationNumber:'',workPlaceId:'',declarantCompanyNumber:'0502635588',applicability:'Te beoordelen',applicabilityReason:'Automatische beoordeling op contractwaarde',thresholdAmount:CHECKINATWORK_THRESHOLD,startDate:new Date().toISOString().slice(0,10),address:projectName,geofenceRadiusMeters:250,environment:'Simulatie',active:true})
  return <div className="modal-backdrop"><form className="modal caw-modal" onSubmit={event=>{event.preventDefault();onSubmit(form)}}><header className="modal-head"><div><p className="eyebrow">Aangifte van Werken</p><h2>RSZ-werkplaats configureren</h2></div><button type="button" className="icon-button" aria-label="Sluiten" onClick={onClose}><XCircle size={19}/></button></header><div className="form-grid"><label>Aangiftenummer<input required value={form.declarationNumber} onChange={event=>setForm({...form,declarationNumber:event.target.value})}/></label><label>Werkplaats-ID<input required value={form.workPlaceId} onChange={event=>setForm({...form,workPlaceId:event.target.value})}/></label><label>Aangever ondernemingsnummer<input required value={form.declarantCompanyNumber} onChange={event=>setForm({...form,declarantCompanyNumber:event.target.value})}/></label><label>Drempel excl. btw<input required type="number" min="0" value={form.thresholdAmount} onChange={event=>setForm({...form,thresholdAmount:Number(event.target.value)})}/></label><label>Startdatum<input required type="date" value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value})}/></label><label>Gepland einde<input type="date" value={form.plannedEndDate??''} onChange={event=>setForm({...form,plannedEndDate:event.target.value||undefined})}/></label><label className="full">Werfadres<input required value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/></label><label>Geofence straal (m)<input type="number" min="10" max="10000" value={form.geofenceRadiusMeters??250} onChange={event=>setForm({...form,geofenceRadiusMeters:Number(event.target.value)})}/></label><label>Omgeving<select value={form.environment} onChange={event=>setForm({...form,environment:event.target.value as typeof form.environment})}><option>Simulatie</option><option disabled={!productionReady}>Productie</option></select></label><label>Voorlopige oplevering<input type="date" value={form.provisionalAcceptanceOn??''} onChange={event=>setForm({...form,provisionalAcceptanceOn:event.target.value||undefined})}/></label><label className="full">Beoordelingsreden<textarea value={form.applicabilityReason} onChange={event=>setForm({...form,applicabilityReason:event.target.value})}/></label></div>{!productionReady&&<div className="caw-form-warning"><AlertTriangle size={16}/>Productie wordt pas beschikbaar nadat de beveiligde adapter en RSZ-middelen zijn geconfigureerd.</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Annuleren</button><button className="primary"><MapPin size={15}/>Werkplaats opslaan</button></div></form></div>
}
