import { useState, type FormEvent } from 'react'
import { X } from 'lucide-react'
import { createId, type BouwFlowState, type Project, type ProjectCloseout, type ProjectContract } from './domain'
import type { useBouwFlowStore } from './store'

export type ContractWorkspaceDialog = 'security' | 'correspondence' | 'claim' | 'point' | 'service'

type Props={
  dialog:ContractWorkspaceDialog
  state:BouwFlowState
  actions:ReturnType<typeof useBouwFlowStore>['actions']
  project?:Project
  contract?:ProjectContract
  closeout?:ProjectCloseout
  onClose:()=>void
}

const employeeName=(employee:BouwFlowState['employees'][number])=>`${employee.firstName} ${employee.lastName}`.trim()

export default function ContractWorkspaceDialogs({dialog,state,actions,project,contract,closeout,onClose}:Props){
  const [security,setSecurity]=useState<{type:'Borgstelling'|'Bankgarantie'|'Verzekering';reference:string;issuer:string;amount:number;expiresOn:string}>({type:'Borgstelling',reference:'',issuer:'',amount:0,expiresOn:''})
  const [correspondence,setCorrespondence]=useState<{date:string;type:'Brief'|'E-mail'|'Verslag'|'Ingebrekestelling'|'Termijnmelding';subject:string;sender:string;recipient:string;documentId:string}>({date:new Date().toISOString().slice(0,10),type:'Brief',subject:'',sender:'',recipient:'',documentId:''})
  const [claim,setClaim]=useState({number:'',title:'',amount:0,scheduleImpactDays:0})
  const [point,setPoint]=useState({description:'',responsible:'',dueDate:'',location:'',workPackageId:'',photoIds:[] as string[]})
  const [service,setService]=useState({title:'',description:'',reportedAt:new Date().toISOString().slice(0,10)})
  const projectDocuments=state.documents.filter(item=>item.projectId===project?.id)
  const projectPhotos=state.sitePhotos.filter(item=>item.projectId===project?.id)
  const submit=(event:FormEvent)=>event.preventDefault()
  const head=(eyebrow:string,title:string)=><div className="modal-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" className="icon-button" aria-label="Sluiten" onClick={onClose}><X size={20}/></button></div>
  const actionsRow=(label:string)=><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Annuleren</button><button className="primary">{label}</button></div>

  if(dialog==='security'&&contract)return <div className="modal-backdrop"><form className="modal contract-workspace-dialog" onSubmit={event=>{submit(event);void actions.updateProjectContract(contract.id,{securities:[...(contract.securities??[]),{id:createId(),...security,expiresOn:security.expiresOn||undefined,status:'Actief'}]});onClose()}}>{head('Contractzekerheid','Zekerheid of verzekering registreren')}<div className="contract-dialog-form"><label>Type<select value={security.type} onChange={event=>setSecurity({...security,type:event.target.value as typeof security.type})}>{['Borgstelling','Bankgarantie','Verzekering'].map(value=><option key={value}>{value}</option>)}</select></label><label>Referentie<input required value={security.reference} onChange={event=>setSecurity({...security,reference:event.target.value})}/></label><label>Uitgever<input required value={security.issuer} onChange={event=>setSecurity({...security,issuer:event.target.value})}/></label><label>Bedrag<input required type="number" min="0" value={security.amount} onChange={event=>setSecurity({...security,amount:Number(event.target.value)})}/></label><label>Vervaldatum<input type="date" value={security.expiresOn} onChange={event=>setSecurity({...security,expiresOn:event.target.value})}/></label></div>{actionsRow('Registreren')}</form></div>

  if(dialog==='correspondence'&&contract)return <div className="modal-backdrop"><form className="modal contract-workspace-dialog" onSubmit={event=>{submit(event);void actions.updateProjectContract(contract.id,{correspondence:[...(contract.correspondence??[]),{id:createId(),...correspondence,documentId:correspondence.documentId||undefined}]});onClose()}}>{head('Formele communicatie','Correspondentie registreren')}<div className="contract-dialog-form"><label>Type<select value={correspondence.type} onChange={event=>setCorrespondence({...correspondence,type:event.target.value as typeof correspondence.type})}>{['Brief','E-mail','Verslag','Ingebrekestelling','Termijnmelding'].map(value=><option key={value}>{value}</option>)}</select></label><label>Datum<input required type="date" value={correspondence.date} onChange={event=>setCorrespondence({...correspondence,date:event.target.value})}/></label><label className="wide">Onderwerp<input required value={correspondence.subject} onChange={event=>setCorrespondence({...correspondence,subject:event.target.value})}/></label><label>Afzender<input required value={correspondence.sender} onChange={event=>setCorrespondence({...correspondence,sender:event.target.value})}/></label><label>Ontvanger<input required value={correspondence.recipient} onChange={event=>setCorrespondence({...correspondence,recipient:event.target.value})}/></label><label className="wide">Document<select value={correspondence.documentId} onChange={event=>setCorrespondence({...correspondence,documentId:event.target.value})}><option value="">Geen document</option>{projectDocuments.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div>{actionsRow('Registreren')}</form></div>

  if(dialog==='claim'&&contract)return <div className="modal-backdrop"><form className="modal contract-workspace-dialog" onSubmit={event=>{submit(event);void actions.createProjectClaim({projectId:contract.projectId,type:claim.scheduleImpactDays>0?'Termijnverlenging':'Financiële claim',cause:claim.title,description:claim.title,amount:claim.amount,extensionDays:claim.scheduleImpactDays,responsibleParty:'Opdrachtgever',documentIds:[],createdBy:state.companyUsers.find(item=>item.id===state.currentUserId)?.displayName??'Projectmanager'});onClose()}}>{head('Contractbeheersing','Claim of termijnverlenging registreren')}<div className="contract-dialog-form"><label>Claimnummer<input required value={claim.number} onChange={event=>setClaim({...claim,number:event.target.value})}/></label><label>Titel<input required value={claim.title} onChange={event=>setClaim({...claim,title:event.target.value})}/></label><label>Bedrag<input type="number" value={claim.amount} onChange={event=>setClaim({...claim,amount:Number(event.target.value)})}/></label><label>Termijnimpact in dagen<input type="number" value={claim.scheduleImpactDays} onChange={event=>setClaim({...claim,scheduleImpactDays:Number(event.target.value)})}/></label></div>{actionsRow('Claim registreren')}</form></div>

  if(dialog==='point'&&closeout)return <div className="modal-backdrop"><form className="modal contract-workspace-dialog" onSubmit={event=>{submit(event);void actions.addCloseoutItem(closeout.id,{...point,workPackageId:point.workPackageId||undefined});onClose()}}>{head('Punchlist','Opleverpunt toevoegen')}<div className="contract-dialog-form"><label className="wide">Opleverpunt<input required value={point.description} onChange={event=>setPoint({...point,description:event.target.value})}/></label><label>Verantwoordelijke<select required value={point.responsible} onChange={event=>setPoint({...point,responsible:event.target.value})}><option value="">Selecteer verantwoordelijke</option>{state.employees.filter(item=>item.active).map(item=><option key={item.id} value={employeeName(item)}>{employeeName(item)} · {item.role}</option>)}</select></label><label>Deadline<input required type="date" value={point.dueDate} onChange={event=>setPoint({...point,dueDate:event.target.value})}/></label><label>Locatie<input value={point.location} onChange={event=>setPoint({...point,location:event.target.value})}/></label><label>Werkpakket<select value={point.workPackageId} onChange={event=>setPoint({...point,workPackageId:event.target.value})}><option value="">Geen werkpakket</option>{project?.workPackages.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label className="wide">Werffoto’s<select multiple value={point.photoIds} onChange={event=>setPoint({...point,photoIds:Array.from(event.currentTarget.selectedOptions,option=>option.value)})}>{projectPhotos.map(item=><option key={item.id} value={item.id}>{item.caption||item.fileName}</option>)}</select></label></div>{actionsRow('Punt toevoegen')}</form></div>

  if(dialog==='service'&&closeout)return <div className="modal-backdrop"><form className="modal contract-workspace-dialog" onSubmit={event=>{submit(event);void actions.addServiceRequest(closeout.id,service);onClose()}}>{head('Garantie en nazorg','Serviceaanvraag registreren')}<div className="contract-dialog-form"><label>Titel<input required value={service.title} onChange={event=>setService({...service,title:event.target.value})}/></label><label>Meldingsdatum<input required type="date" value={service.reportedAt} onChange={event=>setService({...service,reportedAt:event.target.value})}/></label><label className="wide">Beschrijving<textarea required rows={4} value={service.description} onChange={event=>setService({...service,description:event.target.value})}/></label></div>{actionsRow('Registreren')}</form></div>
  return null
}
