import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import QRCode from 'qrcode'
import { AlertTriangle, ArrowRight, Calculator, Camera, CheckCircle2, ClipboardCheck, FileCheck2, Layers3, Plus, ScanLine, Search, ShieldCheck, Smartphone, Sparkles, Wrench, X } from 'lucide-react'
import type { LidarScanInput, LidarScanSession } from './lidar-bim'
import { buildLidarCalculationProposal, LIDAR_WORK_CATALOG, lidarCalculationReadiness, type LidarSurveyElement, type LidarWorkAssignment } from './lidar-calculation'

export type LidarCalculationPersistence = {
  list:(calculationId:string)=>Promise<LidarScanSession[]>
  create:(calculationId:string,input:LidarScanInput)=>Promise<LidarScanSession|undefined>
  build:(scanId:string,elements:LidarSurveyElement[],assignments:LidarWorkAssignment[])=>Promise<LidarScanSession|undefined>
  approve:(scanId:string,approvedBy:string)=>Promise<LidarScanSession|undefined>
  apply:(scanId:string)=>Promise<LidarScanSession|undefined>
}

type Props={calculationId:string;calculationNumber:string;projectName:string;actor:string;persistence?:LidarCalculationPersistence;onApplied:(count:number)=>void;onClose:()=>void}
const phases=[{id:1,label:'Scanopdracht',icon:Smartphone},{id:2,label:'Elementen & werken',icon:Wrench},{id:3,label:'Meet- en kostenreview',icon:ClipboardCheck},{id:4,label:'Calculatie toepassen',icon:Calculator}] as const
const number=(value:number,digits=2)=>new Intl.NumberFormat('nl-BE',{maximumFractionDigits:digits}).format(value)
const money=(value:number)=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(value)
const uuid=(tail:string)=>`00000000-0000-4000-8000-${tail.padStart(12,'0')}`

const demoElements:LidarSurveyElement[]=[
  {id:'scan-room-living',roomId:'living',roomName:'Leefruimte',kind:'Ruimte',label:'Leefruimte',areaM2:34.8,lengthM:24.6,confidencePct:98,photoArtifactIds:['photo-living']},
  {id:'scan-wall-living-1',roomId:'living',roomName:'Leefruimte',kind:'Wand',label:'Wanden leefruimte',areaM2:82.4,netAreaM2:72.6,confidencePct:96,photoArtifactIds:['photo-living']},
  {id:'scan-floor-living',roomId:'living',roomName:'Leefruimte',kind:'Vloer',label:'Vloer leefruimte',areaM2:34.8,confidencePct:98,photoArtifactIds:['photo-living']},
  {id:'scan-sockets-living',roomId:'living',roomName:'Leefruimte',kind:'Stopcontact',label:'Stopcontacten leefruimte',count:8,confidencePct:91,photoArtifactIds:['photo-elec']},
  {id:'scan-lights-living',roomId:'living',roomName:'Leefruimte',kind:'Lichtpunt',label:'Lichtpunten leefruimte',count:5,confidencePct:89,photoArtifactIds:['photo-elec']},
  {id:'scan-room-bath',roomId:'bath',roomName:'Badkamer',kind:'Ruimte',label:'Badkamer',areaM2:9.7,lengthM:13.1,confidencePct:97,photoArtifactIds:['photo-bath']},
  {id:'scan-wall-bath',roomId:'bath',roomName:'Badkamer',kind:'Wand',label:'Wanden badkamer',areaM2:35.2,netAreaM2:31.4,confidencePct:95,photoArtifactIds:['photo-bath']},
  {id:'scan-floor-bath',roomId:'bath',roomName:'Badkamer',kind:'Vloer',label:'Vloer badkamer',areaM2:9.7,confidencePct:97,photoArtifactIds:['photo-bath']},
  {id:'scan-water-bath',roomId:'bath',roomName:'Badkamer',kind:'Leiding',label:'Waterleidingen badkamer',lengthM:18.5,confidencePct:82,photoArtifactIds:['photo-bath-tech']},
  {id:'scan-drain-bath',roomId:'bath',roomName:'Badkamer',kind:'Afvoer',label:'Afvoerleidingen badkamer',lengthM:8.2,confidencePct:79,photoArtifactIds:['photo-bath-tech']},
  {id:'scan-sanitary-bath',roomId:'bath',roomName:'Badkamer',kind:'Sanitair toestel',label:'Wastafel, douche en toilet',count:3,confidencePct:93,photoArtifactIds:['photo-bath']},
  {id:'scan-vent-house',roomId:'technical',roomName:'Technische ruimte',kind:'Ventilatiekanaal',label:'Ventilatiekanalen',lengthM:26.4,confidencePct:86,photoArtifactIds:['photo-hvac']},
  {id:'scan-board-house',roomId:'technical',roomName:'Technische ruimte',kind:'Elektrisch bord',label:'Elektrisch verdeelbord',count:1,confidencePct:94,photoArtifactIds:['photo-elec']},
  {id:'scan-detectors',roomId:'circulation',roomName:'Nachthal',kind:'Detector',label:'Rookdetectoren',count:3,confidencePct:90,photoArtifactIds:['photo-fire']},
]

const demoAssignments:LidarWorkAssignment[]=[
  {id:uuid('1'),catalogCode:'SCH-010',elementIds:['scan-wall-living-1'],photoArtifactIds:['photo-living'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('2'),catalogCode:'VLO-020',elementIds:['scan-floor-bath'],photoArtifactIds:['photo-bath'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('3'),catalogCode:'VLO-030',elementIds:['scan-wall-bath'],photoArtifactIds:['photo-bath'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('4'),catalogCode:'ELE-010',elementIds:['scan-sockets-living'],photoArtifactIds:['photo-elec'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('5'),catalogCode:'ELE-030',elementIds:['scan-lights-living'],photoArtifactIds:['photo-elec'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('6'),catalogCode:'SAN-010',elementIds:['scan-water-bath'],photoArtifactIds:['photo-bath-tech'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('7'),catalogCode:'SAN-020',elementIds:['scan-drain-bath'],photoArtifactIds:['photo-bath-tech'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('8'),catalogCode:'HVA-040',elementIds:['scan-vent-house'],photoArtifactIds:['photo-hvac'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('9'),catalogCode:'ELE-070',elementIds:['scan-board-house'],photoArtifactIds:['photo-elec'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
  {id:uuid('10'),catalogCode:'BRD-010',elementIds:['scan-detectors'],photoArtifactIds:['photo-fire'],dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true},
]

const localSession=(props:Props):LidarScanSession=>({id:uuid('901'),calculationId:props.calculationId,purpose:'Calculatie-opname',modelId:`roomplan-${props.calculationId}`,modelName:`LiDAR-opname · ${props.projectName}`,modelVersion:'RoomPlan-01',zone:'Leefruimte, badkamer en technieken',storey:'Gelijkvloers',deviceName:'iPhone Pro · LiDAR',deviceSupportsLidar:true,captureMode:'Gecombineerd',status:'Opgenomen',capturedBy:props.actor,capturedAt:new Date().toISOString(),notes:'Calculatie-opname met geometrie, foto’s en benoemde werken.',controlPoints:[],artifacts:[{id:'photo-living',kind:'Foto',fileName:'leefruimte.heic',mimeType:'image/heic',sizeBytes:2450000,capturedAt:new Date().toISOString()},{id:'roomplan-demo',kind:'RoomPlan JSON',fileName:'BouwFlow-RoomPlan.json',mimeType:'application/json',sizeBytes:184000,capturedAt:new Date().toISOString()},{id:'usdz-demo',kind:'USDZ',fileName:'BouwFlow-RoomPlan.usdz',mimeType:'model/vnd.usdz+zip',sizeBytes:8240000,capturedAt:new Date().toISOString()}],observations:[],matches:[],progressProposals:[],bcfTopics:[],asBuiltRevisions:[],surveyElements:demoElements,workAssignments:demoAssignments})

export default function LidarCalculationWorkspace(props:Props){
  const [phase,setPhase]=useState<(typeof phases)[number]['id']>(1)
  const [session,setSession]=useState<LidarScanSession>(()=>localSession(props))
  const [elements,setElements]=useState<LidarSurveyElement[]>(demoElements)
  const [assignments,setAssignments]=useState<LidarWorkAssignment[]>(demoAssignments)
  const [selectedElements,setSelectedElements]=useState<Set<string>>(new Set())
  const [catalogCode,setCatalogCode]=useState('ELE-010')
  const [discipline,setDiscipline]=useState('Alle')
  const [query,setQuery]=useState('')
  const [notice,setNotice]=useState('Scanopdracht klaar. Open ze op de iPhone of laad de ontvangen RoomPlan-opname.')
  const [busy,setBusy]=useState(false)
  const [actor,setActor]=useState(props.actor)
  const [qrImage,setQrImage]=useState('')
  const QrCode=({size}:{size:number})=>qrImage?<img src={qrImage} width={size} height={size} alt={`QR-code voor ${props.calculationNumber}`}/>:<ScanLine size={size}/>
  const proposal=session.calculationProposal
  const readiness=lidarCalculationReadiness(elements,assignments,proposal)
  const disciplines=['Alle',...new Set(LIDAR_WORK_CATALOG.map(item=>item.discipline))]
  const catalog=useMemo(()=>LIDAR_WORK_CATALOG.filter(item=>(discipline==='Alle'||item.discipline===discipline)&&(!query||`${item.code} ${item.name} ${item.discipline}`.toLowerCase().includes(query.toLowerCase()))),[discipline,query])
  const selectedDefinition=LIDAR_WORK_CATALOG.find(item=>item.code===catalogCode)
  const compatibleElements=selectedDefinition?elements.filter(item=>selectedDefinition.elementKinds.includes(item.kind)):elements
  const qrPayload=`bouwflowscan://scan?calculation=${encodeURIComponent(props.calculationId)}&purpose=calculation`

  useEffect(()=>{if(!props.persistence)return;void props.persistence.list(props.calculationId).then(items=>{if(items[0]){setSession(items[0]);setElements(items[0].surveyElements?.length?items[0].surveyElements:demoElements);setAssignments(items[0].workAssignments?.length?items[0].workAssignments:demoAssignments);setNotice('Laatste LiDAR-calculatieopname veilig uit BouwFlow geladen.')}})},[props.calculationId,props.persistence])
  useEffect(()=>{void QRCode.toDataURL(qrPayload,{width:220,margin:1,color:{dark:'#102f35',light:'#ffffff'}}).then(setQrImage)},[qrPayload])
  const ensureRemote=async()=>{if(session.id&&!session.id.startsWith('00000000-0000-4000-8000-000000000901'))return session;if(!props.persistence)return session;const input:LidarScanInput={modelId:session.modelId,modelName:session.modelName,modelVersion:session.modelVersion,zone:session.zone,storey:session.storey,deviceName:session.deviceName,deviceSupportsLidar:true,captureMode:session.captureMode,capturedBy:actor||props.actor,capturedAt:session.capturedAt,notes:session.notes,purpose:'Calculatie-opname',surveyElements:elements,workAssignments:assignments};const saved=await props.persistence.create(props.calculationId,input);if(saved)setSession(saved);return saved??session}
  const build=async()=>{setBusy(true);try{const current=await ensureRemote();const saved=await props.persistence?.build(current.id,elements,assignments);const calculationProposal=saved?.calculationProposal??buildLidarCalculationProposal(current.id,props.calculationId,elements,assignments);setSession(saved??({...current,surveyElements:elements,workAssignments:assignments,calculationProposal,status:'Ter goedkeuring'}));setNotice(`${calculationProposal.items.length} calculatieposten voorgesteld voor ${money(calculationProposal.directCost)} directe kost.`);setPhase(3)}catch(error){setNotice(error instanceof Error?error.message:'Calculatieanalyse mislukt')}finally{setBusy(false)}}
  const approve=async()=>{if(!proposal)return;setBusy(true);try{const saved=await props.persistence?.approve(session.id,actor);setSession(saved??({...session,calculationProposal:{...proposal,status:'Goedgekeurd',approvedBy:actor,approvedAt:new Date().toISOString()},status:'Goedgekeurd'}));setNotice(`Meet- en kostenvoorstel goedgekeurd door ${actor}.`);setPhase(4)}catch(error){setNotice(error instanceof Error?error.message:'Goedkeuring mislukt')}finally{setBusy(false)}}
  const apply=async()=>{if(!proposal)return;setBusy(true);try{const saved=await props.persistence?.apply(session.id);const count=saved?.calculationProposal?.createdItemIds?.length??proposal.items.length;setSession(saved??({...session,calculationProposal:{...proposal,status:'Toegepast',appliedAt:new Date().toISOString()}}));setNotice(`${count} herleidbare LiDAR-posten zijn aan ${props.calculationNumber} toegevoegd.`);props.onApplied(count)}catch(error){setNotice(error instanceof Error?error.message:'Toepassen op calculatie mislukt')}finally{setBusy(false)}}
  const addAssignment=()=>{if(!selectedElements.size)return;const id=crypto.randomUUID();const photoArtifactIds=[...new Set(elements.filter(item=>selectedElements.has(item.id)).flatMap(item=>item.photoArtifactIds))];setAssignments(current=>[...current,{id,catalogCode,elementIds:[...selectedElements],photoArtifactIds,dailyReportIds:[],inspectionDocumentIds:[],manuallyConfirmed:true}]);setSelectedElements(new Set());setNotice(`${selectedDefinition?.name??catalogCode} gekoppeld aan ${selectedElements.size} scanobject(en).`)}

  return <div className="modal-backdrop lidar-calculation-backdrop"><section className="modal lidar-calculation-workspace" aria-label="LiDAR-calculatie">
    <header className="lidar-calculation-header"><div className="lidar-brand"><ScanLine size={24}/></div><div><p className="eyebrow">iPhone LiDAR · scan naar calculatie</p><h2>{props.projectName}</h2><span>{props.calculationNumber} · {session.zone}</span></div><div className="lidar-calculation-status"><strong>{session.purpose??'Calculatie-opname'}</strong><small>{session.deviceName}</small></div><button className="icon-button" aria-label="LiDAR-calculatie sluiten" onClick={props.onClose}><X size={20}/></button></header>
    <nav className="lidar-calculation-phases">{phases.map(item=>{const Icon=item.icon;return <button key={item.id} className={`${phase===item.id?'active':''} ${item.id<phase?'complete':''}`} onClick={()=>setPhase(item.id)}><Icon size={16}/><span><b>Fase {item.id}</b>{item.label}</span>{item.id<4&&<ArrowRight size={13}/>}</button>})}</nav>
    <div className="lidar-notice"><Sparkles size={14}/><span>{notice}</span></div>
    <div className="lidar-calculation-body">
      {phase===1&&<div className="lidar-calculation-stage"><section className="lidar-calc-intro"><div><p className="eyebrow">Scanopdracht voor calculatie</p><h3>Open deze calculatie rechtstreeks op de iPhone</h3><p>RoomPlan, ARKit-mesh, foto’s en elementlabels worden als één controleerbaar opnamepakket verzonden.</p><code>{qrPayload}</code></div><div className="lidar-qr"><QrCode size={92}/><strong>Scan met BouwFlow Scan</strong><small>{props.calculationNumber}</small></div></section><div className="lidar-calc-kpis"><div><ScanLine/><span><strong>{elements.length}</strong>scanobjecten</span></div><div><Camera/><span><strong>{session.artifacts.filter(item=>item.kind==='Foto').length}</strong>fotoreeksen</span></div><div><Layers3/><span><strong>{new Set(elements.map(item=>item.roomId)).size}</strong>ruimtes/zones</span></div><div><ShieldCheck/><span><strong>SHA-256</strong>bewijscontrole</span></div></div><section className="lidar-scan-room-map">{[...new Set(elements.map(item=>item.roomName))].map((room,index)=><article key={room} style={{'--room-index':index} as CSSProperties}><strong>{room}</strong><span>{elements.filter(item=>item.roomName===room).length} elementen</span></article>)}</section><button className="primary lidar-next" onClick={()=>setPhase(2)}>Elementen en werken benoemen<ArrowRight size={15}/></button></div>}
      {phase===2&&<div className="lidar-assignment-grid"><aside><div className="lidar-search"><Search size={14}/><input placeholder="Zoek werk, techniek of code" value={query} onChange={event=>setQuery(event.target.value)}/></div><select value={discipline} onChange={event=>setDiscipline(event.target.value)}>{disciplines.map(item=><option key={item}>{item}</option>)}</select><div className="lidar-work-catalog">{catalog.map(item=><button key={item.code} className={catalogCode===item.code?'selected':''} onClick={()=>{setCatalogCode(item.code);setSelectedElements(new Set())}}><b>{item.code}</b><strong>{item.name}</strong><span>{item.discipline} · {item.unit}</span></button>)}</div></aside><main><header><div><p className="eyebrow">Geselecteerd werk</p><h3>{selectedDefinition?.name}</h3><span>{selectedDefinition?.description}</span></div><button className="primary" disabled={!selectedElements.size} onClick={addAssignment}><Plus size={15}/>Werk koppelen ({selectedElements.size})</button></header><div className="lidar-element-picker">{compatibleElements.map(item=><label key={item.id} className={selectedElements.has(item.id)?'selected':''}><input type="checkbox" checked={selectedElements.has(item.id)} onChange={()=>setSelectedElements(current=>{const next=new Set(current);if(next.has(item.id))next.delete(item.id);else next.add(item.id);return next})}/><span><b>{item.label}</b><small>{item.roomName} · {item.kind}</small></span><em>{item.netAreaM2??item.areaM2??item.lengthM??item.count??1} {item.netAreaM2||item.areaM2?'m²':item.lengthM?'m':'st'}</em><i>{item.confidencePct}%</i></label>)}</div><section className="lidar-assignment-summary"><h4>Toegevoegde werken <span>{assignments.length}</span></h4>{assignments.map(item=>{const definition=LIDAR_WORK_CATALOG.find(entry=>entry.code===item.catalogCode);return <article key={item.id}><CheckCircle2 size={15}/><span><strong>{definition?.name}</strong><small>{item.elementIds.length} objecten · {definition?.discipline}</small></span><button className="icon-button" aria-label="Werk verwijderen" onClick={()=>setAssignments(current=>current.filter(entry=>entry.id!==item.id))}><X size={14}/></button></article>})}<button className="primary" disabled={!assignments.length||busy} onClick={build}>{busy?'Analyseren…':'Meetstaat en kosten berekenen'}<ArrowRight size={15}/></button></section></main></div>}
      {phase===3&&<div className="lidar-review"><header><div><p className="eyebrow">Menselijke controle verplicht</p><h3>Meet- en kostenvoorstel</h3><span>LiDAR levert geometrie; foto’s, dagrapporten, bevestiging en keuringen dekken niet-zichtbare prestaties.</span></div><label>Goedgekeurd door<input value={actor} onChange={event=>setActor(event.target.value)}/></label></header><div className="lidar-review-kpis"><div><span>Posten</span><strong>{proposal?.items.length??0}</strong></div><div><span>Directe kost</span><strong>{money(proposal?.directCost??0)}</strong></div><div><span>Te controleren</span><strong>{proposal?.items.filter(item=>item.reviewReasons.length).length??0}</strong></div><div><span>Gemiddelde zekerheid</span><strong>{number((proposal?.items.reduce((sum,item)=>sum+item.confidencePct,0)??0)/(proposal?.items.length||1),1)}%</strong></div></div><div className="lidar-review-table"><div className="head"><span>Post / ruimte</span><span>Hoeveelheid</span><span>Eenheidskost</span><span>Bewijs</span><span>Controle</span></div>{proposal?.items.map(item=><article key={item.id}><span><b>{item.catalogCode} · {item.boqItem.description}</b><small>{item.roomNames.join(', ')} · {item.sourceElementIds.length} scanobjecten</small></span><strong>{number(item.quantity,3)} {item.unit}</strong><strong>{money(item.boqItem.labor+item.boqItem.material+item.boqItem.equipment+item.boqItem.subcontracting)}</strong><em className={item.evidenceComplete?'ok':'warn'}>{item.evidenceComplete?'Compleet':'Aanvullen'}</em><span>{item.reviewReasons.length?item.reviewReasons.map(reason=><small key={reason}><AlertTriangle size={11}/>{reason}</small>):<small className="ok"><CheckCircle2 size={11}/>Meetregel conform</small>}</span></article>)}</div><button className="primary lidar-next" disabled={!proposal||!actor.trim()||busy} onClick={approve}><ShieldCheck size={15}/>{busy?'Goedkeuren…':'Voorstel menselijk goedkeuren'}</button></div>}
      {phase===4&&<div className="lidar-apply"><div className="lidar-apply-hero"><FileCheck2 size={42}/><p className="eyebrow">Gecontroleerde LiDAR-calculatie</p><h3>{proposal?.items.length??0} posten klaar voor {props.calculationNumber}</h3><p>Elke post bewaart de bronruimte, scanobjecten, meetregel, zekerheid en bewijsverwijzingen. Bij gunning wordt deze opname automatisch de projectnulmeting.</p></div><div className="lidar-readiness-grid">{[['Geometrie beschikbaar',readiness.geometryAvailable],['Werken benoemd',readiness.worksAssigned],['Bewijs beoordeeld',readiness.evidenceComplete],['Menselijk goedgekeurd',readiness.reviewed],['Toegepast op calculatie',readiness.applied]].map(([label,ready])=><div key={String(label)} className={ready?'ready':''}>{ready?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}<span>{label}</span></div>)}</div><section className="lidar-evidence-policy"><ShieldCheck size={22}/><div><strong>Hybride bewijsregel actief</strong><p>LiDAR-meting + foto’s + goedgekeurde dagrapporten + manuele bevestiging + eventuele keuringsdocumenten. Onzichtbare of technisch kritieke werken blijven geblokkeerd voor automatische certificatie.</p></div></section><button className="primary lidar-apply-button" disabled={proposal?.status!=='Goedgekeurd'||busy} onClick={apply}><Calculator size={17}/>{proposal?.status==='Toegepast'?'Reeds toegepast':busy?'Calculatie bijwerken…':'Posten aan calculatie toevoegen'}</button></div>}
    </div>
  </section></div>
}
