import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, CheckCircle2, ExternalLink, Link2, Mail, Paperclip, RefreshCw, Search, Send } from 'lucide-react'
import type { BouwFlowState, MailboxComposeInput, MailboxLinkInput, MailboxMessage, MailboxOverview } from './domain'

interface MailboxActions {
  mailbox():Promise<MailboxOverview>
  synchronizeMailbox():Promise<MailboxOverview>
  sendMailboxMessage(input:MailboxComposeInput):Promise<MailboxMessage|undefined>
  linkMailboxMessage(id:string,input:MailboxLinkInput):Promise<MailboxMessage|undefined>
}

export default function MailboxPage({state,actions}:{state:BouwFlowState;actions:MailboxActions}) {
  const [overview,setOverview]=useState<MailboxOverview>({configured:false,mailbox:'',messages:[]})
  const [loading,setLoading]=useState(true);const [syncing,setSyncing]=useState(false);const [sending,setSending]=useState(false)
  const [error,setError]=useState('');const [query,setQuery]=useState('');const [direction,setDirection]=useState<'Alle'|'Inkomend'|'Uitgaand'>('Alle')
  const [selectedId,setSelectedId]=useState<string>();const [composeOpen,setComposeOpen]=useState(false)
  const [compose,setCompose]=useState({to:'',cc:'',subject:'',body:'',organizationId:'',opportunityId:'',projectId:''})
  const selected=overview.messages.find(item=>item.id===selectedId)

  const load=async(sync=false)=>{try{setError('');if(sync)setSyncing(true);else setLoading(true);const result=sync?await actions.synchronizeMailbox():await actions.mailbox();setOverview(result);setSelectedId(current=>current&&result.messages.some(item=>item.id===current)?current:result.messages[0]?.id)}catch(value){setError(value instanceof Error?value.message:'De mailbox kon niet worden geladen.')}finally{setLoading(false);setSyncing(false)}}
  useEffect(()=>{let active=true;void actions.mailbox().then(result=>{if(!active)return;setOverview(result);setSelectedId(result.messages[0]?.id);setLoading(false);if(result.configured)void actions.synchronizeMailbox().then(fresh=>{if(active){setOverview(fresh);setSelectedId(current=>current??fresh.messages[0]?.id)}}).catch(value=>{if(active)setError(value instanceof Error?value.message:'Synchronisatie mislukt')})}).catch(value=>{if(active){setError(value instanceof Error?value.message:'De mailbox kon niet worden geladen.');setLoading(false)}});return()=>{active=false}},[actions])
  const messages=useMemo(()=>overview.messages.filter(item=>(direction==='Alle'||item.direction===direction)&&`${item.subject} ${item.fromName} ${item.fromAddress} ${item.bodyPreview}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[overview.messages,direction,query])
  const relationLabel=(message:MailboxMessage)=>message.projectId?state.projects.find(item=>item.id===message.projectId)?.number:message.opportunityId?state.opportunities.find(item=>item.id===message.opportunityId)?.projectNumber:message.organizationId?state.organizations.find(item=>item.id===message.organizationId)?.name:undefined
  const send=async(event:FormEvent)=>{event.preventDefault();setSending(true);setError('');try{const input:MailboxComposeInput={to:compose.to.split(/[;,\n]/).map(item=>item.trim()).filter(Boolean),cc:compose.cc.split(/[;,\n]/).map(item=>item.trim()).filter(Boolean),subject:compose.subject,body:compose.body,organizationId:compose.organizationId||undefined,opportunityId:compose.opportunityId||undefined,projectId:compose.projectId||undefined};const message=await actions.sendMailboxMessage(input);if(message)setOverview(current=>({...current,messages:[message,...current.messages]}));setComposeOpen(false);setCompose({to:'',cc:'',subject:'',body:'',organizationId:'',opportunityId:'',projectId:''})}catch(value){setError(value instanceof Error?value.message:'E-mail kon niet worden verzonden.')}finally{setSending(false)}}
  const saveLink=async(input:MailboxLinkInput)=>{if(!selected)return;try{const updated=await actions.linkMailboxMessage(selected.id,input);if(updated)setOverview(current=>({...current,messages:current.messages.map(item=>item.id===updated.id?updated:item)}))}catch(value){setError(value instanceof Error?value.message:'Koppeling kon niet worden opgeslagen.')}}
  return <div className="mailbox-page">
    <section className="panel mailbox-hero"><div><p className="eyebrow">Microsoft 365</p><h2>Centrale BouwFlow-mailbox</h2><span>Inkomende en uitgaande projectcommunicatie via <strong>{overview.mailbox||'Bouw.Flow@bosis.be'}</strong>.</span></div><div className={`mailbox-connection ${overview.configured?'ready':''}`}>{overview.configured?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<span><strong>{overview.configured?'Verbonden':'Nog niet geactiveerd'}</strong><small>{overview.lastSynchronizedAt?`Laatste sync ${new Date(overview.lastSynchronizedAt).toLocaleString('nl-BE')}`:'Microsoft 365-configuratie vereist'}</small></span></div></section>
    {error&&<div className="mailbox-alert"><AlertTriangle size={17}/><span>{error}</span></div>}
    <section className="panel mailbox-toolbar"><div className="mailbox-tabs">{(['Alle','Inkomend','Uitgaand'] as const).map(item=><button key={item} className={direction===item?'active':''} onClick={()=>setDirection(item)}>{item==='Inkomend'?<ArrowDownLeft size={15}/>:item==='Uitgaand'?<ArrowUpRight size={15}/>:<Mail size={15}/>} {item}</button>)}</div><label className="mailbox-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Zoek op afzender, onderwerp of inhoud…"/></label><button className="secondary" disabled={!overview.configured||syncing} onClick={()=>void load(true)}><RefreshCw size={15} className={syncing?'spin':''}/>{syncing?'Synchroniseren…':'Synchroniseren'}</button><button className="primary" disabled={!overview.configured} onClick={()=>setComposeOpen(true)}><Send size={15}/>Nieuwe e-mail</button></section>
    <div className="mailbox-layout"><section className="panel mailbox-list">{loading?<div className="mailbox-empty">Mailbox laden…</div>:messages.map(message=><button key={message.id} className={selected?.id===message.id?'active':''} onClick={()=>setSelectedId(message.id)}><span className={`mailbox-direction ${message.direction==='Inkomend'?'incoming':'outgoing'}`}>{message.direction==='Inkomend'?<ArrowDownLeft size={15}/>:<ArrowUpRight size={15}/>}</span><span className="mailbox-list-copy"><strong>{message.direction==='Inkomend'?(message.fromName||message.fromAddress):message.toRecipients.map(item=>item.name||item.address).join(', ')}</strong><b>{message.subject}</b><small>{message.bodyPreview}</small></span><span className="mailbox-list-meta"><time>{new Date(message.receivedAt??message.sentAt??message.synchronizedAt).toLocaleDateString('nl-BE',{day:'2-digit',month:'short'})}</time>{message.hasAttachments&&<Paperclip size={13}/>} {relationLabel(message)&&<em>{relationLabel(message)}</em>}</span></button>)}{!loading&&!messages.length&&<div className="mailbox-empty"><Mail size={28}/><strong>Geen e-mails gevonden</strong><span>Pas je zoekopdracht of filter aan.</span></div>}</section>
      <section className="panel mailbox-detail">{selected?<><header><div><p className="eyebrow">{selected.direction}</p><h2>{selected.subject}</h2></div>{selected.webLink&&<a className="secondary" href={selected.webLink} target="_blank" rel="noreferrer">Open in Outlook <ExternalLink size={14}/></a>}</header><dl><div><dt>Van</dt><dd>{selected.fromName||selected.fromAddress} {selected.fromName&&<small>{selected.fromAddress}</small>}</dd></div><div><dt>Aan</dt><dd>{selected.toRecipients.map(item=>item.name||item.address).join(', ')}</dd></div><div><dt>Datum</dt><dd>{new Date(selected.receivedAt??selected.sentAt??selected.synchronizedAt).toLocaleString('nl-BE')}</dd></div></dl><article className="mailbox-preview">{selected.bodyPreview||'Geen tekstvoorbeeld beschikbaar.'}</article><div className="mailbox-linker"><h3><Link2 size={16}/>Koppel aan een BouwFlow-dossier</h3><label>Relatie<select value={selected.organizationId??''} onChange={event=>void saveLink({organizationId:event.target.value||undefined,opportunityId:selected.opportunityId,projectId:selected.projectId})}><option value="">Niet gekoppeld</option>{state.organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Opportuniteit<select value={selected.opportunityId??''} onChange={event=>void saveLink({organizationId:selected.organizationId,opportunityId:event.target.value||undefined,projectId:selected.projectId})}><option value="">Niet gekoppeld</option>{state.opportunities.map(item=><option key={item.id} value={item.id}>{item.projectNumber} · {item.title}</option>)}</select></label><label>Project<select value={selected.projectId??''} onChange={event=>void saveLink({organizationId:selected.organizationId,opportunityId:selected.opportunityId,projectId:event.target.value||undefined})}><option value="">Niet gekoppeld</option>{state.projects.map(item=><option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></label></div></>:<div className="mailbox-empty">Selecteer een bericht om de inhoud te bekijken.</div>}</section></div>
    {composeOpen&&<div className="dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setComposeOpen(false)}}><form className="dialog mailbox-compose" onSubmit={send}><header><div><p className="eyebrow">Van {overview.mailbox}</p><h2>Nieuwe e-mail</h2></div><button type="button" className="secondary" onClick={()=>setComposeOpen(false)}>Sluiten</button></header><label>Aan<input required type="email" value={compose.to} onChange={event=>setCompose({...compose,to:event.target.value})} placeholder="naam@bedrijf.be"/></label><label>CC<input type="email" value={compose.cc} onChange={event=>setCompose({...compose,cc:event.target.value})}/></label><label>Onderwerp<input required value={compose.subject} onChange={event=>setCompose({...compose,subject:event.target.value})}/></label><label>Bericht<textarea required rows={10} value={compose.body} onChange={event=>setCompose({...compose,body:event.target.value})}/></label><div className="mailbox-compose-links"><label>Relatie<select value={compose.organizationId} onChange={event=>setCompose({...compose,organizationId:event.target.value})}><option value="">Geen</option>{state.organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Opportuniteit<select value={compose.opportunityId} onChange={event=>setCompose({...compose,opportunityId:event.target.value})}><option value="">Geen</option>{state.opportunities.map(item=><option key={item.id} value={item.id}>{item.projectNumber} · {item.title}</option>)}</select></label><label>Project<select value={compose.projectId} onChange={event=>setCompose({...compose,projectId:event.target.value})}><option value="">Geen</option>{state.projects.map(item=><option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></label></div><footer><button type="button" className="secondary" onClick={()=>setComposeOpen(false)}>Annuleren</button><button className="primary" disabled={sending}><Send size={15}/>{sending?'Versturen…':'Versturen via Microsoft 365'}</button></footer></form></div>}
  </div>
}
